### ISSUE TITLE
Removed characters are missing from the list when editing entries

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#103]
I added Gabriel to Lantern in the Snow, made a new post, had him involved, and then removed him from the story. He was listed as having been in the story at some point (greyed out). I edited the post which had the one trace of him but obviously couldn't remove him from that post because his name wasn't in the list of related characters. So without changing anything, on hitting Submit, Gabriel was no longer listed as in the story and all traces of him were removed. Is this something we want to happen? It seems a little scrappy to me.

**Comment by Treijim** [comment]
I just noticed he's still listed as previously in the story. Will that never go away, even though there's no longer a trace of him within the story?

**Comment by bheiskell** [comment]
That's definitely an accident. That list is suppose to only include characters that are active in the story. Hence when you edit, he's missing. I'll add a special case to pull down any existing characters already tagged in that entry. Aside from an edit, would we ever want to list deactivated characters, like in a new entry?

Regarding your follow up comment, I could add logic to check if a character was ever referenced in an entry and if not remove him from the story completely. That may get a bit wonky when it comes to imported stories, but I think it's probably worth the effort. I'm creating a second issue for that though. I'll tag that as a 0.2 release issue.

**Comment by bheiskell** [comment]
Resolved this by merging the existing data that&#39;s pulled down with the edit. Closed by 58f9435ead7051ba00d4e8538bdb77c1f147ed82
