### ISSUE TITLE
Story Page Navigation

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#104]
Can we have the navigation at the top of the stories, too? :)

**Comment by bheiskell** [comment]
I'm thinking all links need to be at the top and bottom of the page. When I initially designed it I didn't realize how long the pages would end up. Setting for 0.1 release.

**Comment by bheiskell** [comment]
Added pager to top and bottom of tables. Closed by fb06e6e5b221b479317adf4d38a297ed12d674b2
