### ISSUE TITLE
Mark all as read

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#108]
For the love of god, I have 25 messages that I have to click through to mark as read...

**Comment by Treijim** [comment]
I know right :D

**Comment by bheiskell** [comment]
Added checkbox based mark as read to messages. Added a javascript select all as well. Hacked together a csrf safe mark as read for messages. Still will need a view read messages section at some point. Closed by 542b38af77d6040be6255020d8c6003df4100412
