### ISSUE TITLE
Evan's Avatar

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#110]
Try to update Evan's avatar on the non-dev version with http://treijim.korw.net/Avatars/evan.jpg because for me clicking Update makes the page blank. It's the bug I described before. And with Evan, of all people!

**Comment by bheiskell** [comment]
Ah I know why that's happening. I thought I fixed that!

**Comment by bheiskell** [comment]
Ok, I did not know what was causing that. For some reason the faction id field is being removed. This causes CakePHP's security component to blackhole the request. This doesn't occur when JavaScript is disabled. I'm currently looking into why the javascript is doing that.

In the meantime I'm now redirecting cakephp blackholes from the security component to a 500 error which logs the message and stack trace. This may have security implications that I'm not aware of. However, the benefit outweighs the risk here.

**Comment by bheiskell** [comment]
Interesting, the problem appears to be with the auto selection of a disabled field. I'm pretty certain I can fix this. Strange behavior though. Btw, why is Evan in the guards, huh? ;-)

**Comment by bheiskell** [comment]
Mega hack to deal with the same option showing up in two optgroups. Considering both cakephp and jquery don&#39;t know how to deal with disabled options, I&#39;m thinking this might be undefined behavior. Either way, I should come back and refactor this code to not be divided into two optgroups, or have the relationship between the factions and races be unique in this select drop down. PM let me know if you still have issues. Closed by 057d424503d0e5a1b77f6cb0ee6dbc90833bbdae Closed by 057d424503d0e5a1b77f6cb0ee6dbc90833bbdae
