### ISSUE TITLE
Logged Out

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#112]
I keep getting logged out each time I revisit the site. This is a minor issue, but needs to be addressed at some point.

**Comment by bheiskell** [comment]
This morning, I noticed that all sessions were cleared from PHP's session store. I've switched to a DB based session store in hope that this is a PHP session configuration issue and not a CakePHP issue. Leaving open for now.

**Comment by bheiskell** [comment]
Has this happened again PM?

**Comment by Treijim** [comment]
Rarely, but that was after Firefox updates and other similar things, so I don't think it's to do with our website.

**Comment by bheiskell** [comment]
Closing then. Let me know if the issue resumes.
