### ISSUE TITLE
Moderator Status upon Story Creation

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#114]
Bug from moving from a stories user association to a dynamic association based on characters being added/removed.

**Comment by bheiskell** [comment]
PM, there's no scenario where a user should be able to create a new story when they don't have any available characters right?

**Comment by Treijim** [comment]
That's right.

**Comment by bheiskell** [comment]
There are a few situations I want to consider when resolving this issue. Creating a new story should trigger these events:
- If the user has no free characters because they haven't created any, explain and link to the new character page
- If the user has no free characters because their character is pending, explain the issue
- If the user has no free characters because they have characters in another thread, display their characters and offer a link to remove that character from their active thread
