### ISSUE TITLE
Links to Wiki

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#117]
I noticed a comment in the cbox about links to the wiki etc. What links do we need and where should we place them? This is an easy fix.

**Comment by Treijim** [comment]
Obviously the links will need to be easily edited by me, as I update the wiki and need to update the list to reflect that. I suppose something similar to the wiki's navigation menu would be cool. I'm not sure where it would go. We don't have an Information page like on the old forum. Maybe we should.

**Comment by bheiskell** [comment]
Personally, I think we should have the wiki on riiga.net itself. It wouldn't actually be a wiki anymore, just a structure of information about riiga. How we do that is up to you. I'm working out the details of a markup language for riiga in issue #.
