### ISSUE TITLE
Implement locations for stories.

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#13]
Implement a locations table and integrate it with story creation. I need to discuss this more with the product manager. I'm uncertain if this would require revisioning or some type of special story post.

E.g, a story might start in one location and change locations five times. Without revisioning only the last location will be tracked.

**Comment by Treijim** [comment]
As mentioned, the current forum uses a mix of countries and provinces for story locations. I think that all inhabited areas can be broken down into provinces and stories can happen within those. Let me know when you want a list of provinces, their locations, and their descriptions. 

As a side note, what about theads which occur on the sea? Should they be set in the closest country/province? Also, somewhat related, some regions are unnamed. Perhaps, within the relevant countries, there is a "province" called "wilderness" in which people can post threads. 

Looking for your thoughts.

**Comment by bheiskell** [comment]
Sea could just be ID'd as sea. Wilderness could work, or calling it other.

There can be as many and as few tiers as you want. Once I code support for 2 tiers it's not hard to support some entries only being 1 (sea), or even cities within provinces.

**Comment by Treijim** [comment]
I'll do a table which goes down to minor cities and we can take it as deep as we want then.

**Comment by bheiskell** [comment]
I've implemented a very very basic interface for entering in the locations. Once you finish, let me know when you start and finish; that way, I can make back up of your work. Let me know if you have any questions.

Adjust your testing URL to match this "riiga/alpha/locations/"

**Comment by bheiskell** [comment]
Cleaned up the tree interface on the index page of the locations interface. Still lacks a map / widget, but this should make it easier for the admin to see the current structure of the locations.

**Comment by bheiskell** [comment]
Closing this one to transfer the widget work to the issue set aside for the location widget.
