### ISSUE TITLE
Safari Layout

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#135]
Scraverx is having this problem: http://i27.photobucket.com/albums/c154/scraverx/random_stuff/edit-layout.jpg

I'll assume it's just his Safari browser. Let me know what you think.

**Comment by bheiskell** [comment]
Both chrome and safari render web pages using webkit. I thought this meant I didn't need to test using safari, but that turns out to be an unsafe assumption.

This is seriously embarrassing. This is my second priority behind the recent 500 errors.
