### ISSUE TITLE
Author Name Changes

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#18]
Right now, an author can change their username to something else. They probably should only be able to change the case of it.

**Comment by bheiskell** [comment]
PM, what do you think of this? Should a user be allowed to change their username? I really don't have a problem with this as they'll be identified by their stories and characters. The name is semi-irrelevant.

**Comment by Treijim** [comment]
Don't allow users to change their usernames unless somebody brings it up.

**Comment by bheiskell** [comment]
Closing due to out of band convo.
