### ISSUE TITLE
Character wizard

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#22]
Create a wizard for creating / edting characters.

**Comment by bheiskell** [comment]
This has been branched out into several smaller sub-issues. Macro level notes will be posted here including when the wizard is completed.

**Comment by bheiskell** [comment]
PM: "The rank on your profile has a quantity of stars, equivalent to how many posts you’ve done (use current forum rules)
- <del>When you create a character and give him or her a rank of stars, it must not exceed your own rank</del>
- <del>The character’s rank dictates what race/class/wallet/etc you can choose</del>
- <del>There will be options for context-sensitive drop-down menus enabling easier selection of details</del>
- <del>Residency (country and/or province) is selected first, ideally from a minimap, followed by context-sensitive Rank > Race > Age > Faction > Profession > Wallet, in that order. I’ll create the data lists in the format you need when you need them</del>

**Comment by bheiskell** [comment]
The order is now Rank > Race > Residency > Faction > Profession > Wallet. Age still needs to be added. Another issue is filed for that.

**Comment by bheiskell** [comment]
Any OR (overridable) character wizard options must have an override button. Currently the only non-overridable options are:
- rank
- race
- residency
- faction residency/age/rank limits
- profession limits for certain races

The profession limits aren't enforceable imho. I need clarification on this.

**Comment by bheiskell** [comment]
PM:

<table>
<tr>
<th>Rank</th><th>Posts</th><th>Extra</th>
<th>Race Access</th><th>Wallet</th><th>Rank</th>
</tr>
<tr><td>Foreigner</td><td>0</td><td>20</td><td>Humans, Ildemin</td><td>2</td><td>1</td></tr>
<tr><td>Commoner</td><td>20</td><td>30</td><td>Keid, Gruitin</td><td>20</td><td>2</td></tr>
<tr><td>Citizen</td><td>50</td><td>50</td><td>Sirin</td><td>200</td><td>3</td></tr>
<tr><td>Soldier</td><td>100</td><td>125</td><td>Hamakro</td><td>2000</td><td>4</td></tr>
<tr><td>Guard</td><td>225</td><td>175</td><td>Fanoran</td><td>20,000</td><td>5</td></tr>
<tr><td>Knight</td><td>400</td><td>200</td><td> </td><td>200,000</td><td>6</td></tr>
<tr><td>Commander</td><td>600</td><td> </td><td> </td><td>2,000,000</td><td>7</td></tr>
</table>

Wallet currency is in standard Central currency: Lunam

For more rules:
http://www.etherealpanda.com/misc/files/riiga/forum%20rules.xlsx

Retroactive Note: Wallet was eventually dropped

**Comment by Treijim** [comment]
"The profession limits aren't enforceable imho. I need clarification on this."

Do you mean the age limits or the racial limits? It's plausible to make both OR but as normal all character submissions are subject to me.

**Comment by bheiskell** [comment]
Profession limits will not be programmatically enforced.

**Comment by bheiskell** [comment]
Ok, I spent the last hour and a half writing down how I'm going to implement the character wizard rules in tables. This will give the PM control over the character rules, both wizard and not. The things listed as hard cannot be changed without adding more entries to the tables. The things listed as soft are merely suggestions provided by the character wizard. 

NOR even by admin means that there's no way to override it while creating a character. The admin would have to add new entries/rules to the tables. For instance, you can't create a race by just typing in text. You would have to add the race to Riiga and then select in while creating your character. For special cases we may want to have an unknown race / residency.

Order of rules:
Rank is limited by number of posts (hard)
Residency is limited by rank (hard)
Race is limited by rank (hard)
Race is limited by residency (soft)
Age is limited by race (soft)
Factions are limited by race (hard)
Faction rank is limited age and rank (hard)
Profession is limited by age and race (soft)

<del>ranks - id, name, entry_count (NOR even by admin)
This is the user and character rank. Entry count will be used to determine how many posts are required of a user to obtain this rank.</del>

<del>character_locations - id, location_id, rank_id (NOR even by admin +)
Locations a character can pick from. This will reference the locations already entered into the system. An admin can then select which locations can be chosen for a character. This is only used to populate the list. The character table will then reference the actual locations via location_id.</del>

<del>\+ Any location in Riiga can be used, but it has to be on the full locations page. For instance, Gondarash couldn't be used unless you entered it into the locations admin page. This may lead to a need for an unknown location or 'hidden' locations that can only be selected by an admin.</del>


<del>races - id, name, rank_id (NOR even by admin)
Races and the minimum character rank required to select them.</del>

<del>locations_races - id, character_location_id, race_id, likelyhood (NOR by player)
Suggested likelyhood of a race being in a certain location. This is a little sloppy, because I'm mapping against locations instead of character locations. This means there's not full coverage for likelyhood for all locations. I could compensate by traversing up the location tree until I find a location with a likelyhood though.</del>

<del>race_ages - id, child, teen, adult, mature, elder, max (OR)
Suggested age for a character based on their maturity.</del>

<del>factions - id, name (NOR even by admin +)
List of Riigan factions.</del>

<del>\+ Do we want users to be able to make up faction names? I'd advise against this. If they want their own 'faction' they should put it in the occupation, e.g., bandit of the blue suns. If you want a new faction, simply add it to the factions admin interface.</del>


<del>factions_races - id, faction_id, race_id (NOR by player)
Add races to a faction.</del>

<del>faction_ranks - id, name, faction_id, rank_id, age (NOR even by admin)
Rank names for each faction. Has a minimum character rank and age +.</del>

<del>\+ Age requirement is overridable, but you can't make up a rank without adding it to the ranks table.</del>


<del>professions - id, name (OR)
List of recommended professions. This will be used to populate, but in the end the profession can be whatever text is entered in by the user.</del>

<del>professions_races - id, profession_id, race_id, age (OR)
An entry here implies that a race has this profession and lists the minimum age recommended.</del>

**Comment by Treijim** [comment]
"Do we want users to be able to make up faction names?"
No. But people may suggest new factions to me if they can propose convincing reasons as to why they would exist in Riiga, and then they may use a new faction officially.

Regarding professions, Selden recently commented that some people have multiple professions. Of course this is true, and since this field is OR, the user can simply view and select one or more professions and type in whatever they want, such as "Lumberjack" or "Cabinetmaker, Shipwright". 

The rest looks great to me. Hope I didn't miss any questions.

**Comment by bheiskell** [comment]
All new tables have been created, but the MVC generation has only been done for ranks and residencies. It took longer than I thought it would due to a bug with the view generation. Data is also populated minus one entry in the character locations table that doesn't exist in the locations table yet.

**Comment by bheiskell** [comment]
Added races to the mix. I'll need to come back and clean up the MVC components of these once I'm finished so that they're consistent with the rest of the project.

**Comment by bheiskell** [comment]
Got the location to race likelihood mapping finished.

**Comment by bheiskell** [comment]
Ok I've added ranks and all profession tables. There are now tables, models and controllers for all needed aspects of the character wizard data. I've also populated them from the tasks xls and doc. Scaffolding is still on for a few of the tables. I'll turn that off when I actually move them into admin sections.

PM: An ugly version of the data can be found at these paths. At some point we may want to stream line updates here, but at the same time I don't know how often you'll be modifying the data. So it may be a moot point.
/ranks
/character_locations
/races
/locations_races
/race_ages
/factions
/faction_ranks
/professions
/professions_races

PM: In the xls there are columns that are grey/blank, 0, or contain a ':'. What do these mean? Is 0 the same as blank?

**Comment by bheiskell** [comment]
Ok I'm pretty jazzed. I got quite a bit done on the edit character page. PM: check it out.

All required rules are now visible on the interface; they aren't enforced by the backend yet. It's important to me that all basic functionality be attainable without any ajax/js. Although not pretty, it is usable.

Rank is limited by number of posts (hard)
I need to find a better way to display the user's current rank somewhere. Currently it's in a hidden field. It should be in some text element that is hidden when the star rank is enabled.

Location is limited by rank (hard)
Race is limited by rank (hard)
Used opt groups to break them up. JS will disable based on the rank selected.

Location is limited by race (soft)
I think I'll display this in a table and then use javascript to translate the location name to have (race likely) (race unlikely) or (race possible) next to the location. Alternatively, there are fancy JS select drop downs that should be able to offer me color coded icons.

Age is limited by race (soft)
Another table. In this case rows will simply be hidden by js for unrelated races.

Factions are limited by race (hard)
This needs JS. Currently it's opt grouped, but I think it should only show up with appropriate options a race with a faction is selected.

Faction rank is limited age and rank (hard)
This shows entries and highlights the current rank you qualify for. Both age and rank must be met to qualify for a faction rank. Faction ranks are calculated not selected.

Profession is limited by age and race (soft)
Another context aware table. In this case I'll need an override button so that the user can manually enter in data.

**Comment by bheiskell** [comment]
I've got JS in place for most of the currently available information. I need to take some time with the PM to throw around some interface mockups. The flow of the current UI isn't very good. We need to find a layout that expresses the information in a useful way.

**Comment by bheiskell** [comment]
To clarify, I feel like I have a lot of good individual pieces. We just need to arrange them in a meaningful way.

**Comment by bheiskell** [comment]
Ok I've been hacking around for the last ten days or so and have a decent chunk of the character wizard finished. I did a ton of CSS formatting to get the character wizard into a two column layoutish interface. I leveraged an existing jquery ui select menu and spent a lot of time determining the proper way to extend it. Some of the final data is in place, some of it is mock (ages), and some of it isn't there yet.

I'm going to list the remaining todo so I don't forget:
- <del>Figure out what's wrong with the selectmenu and IE<del>
- PM feels gold stars are too bright in the drop downs.
- <del>Add public interfaces that will update which options are disabled. (This is needed to re-propagate the rules.)</del>
- <del>Ensure the last operation mention resets the selectmenu if the currently selected field is disabled.</del>
- <del>Output the race/age data, location data, race data, and the profession data to html in a way that can be programmatically accessed.</del>
- <del>Ensure that if JS is turned off that the aforementioned data doesn't kill the layout.</del>
- <del>Associate the location and race data to their selectmenus</del>
- <del>Write the pseudo-drilldown for the profession field. This will have the profession categories in column i. Column i+1 to n will the character's race's professions and the corresponding ages. This probably will be best suited with floating li's. </del>
- <del>Apply the race age data to the age's field. Probably the easiest out of this list.</del>
- <del>Fix the NPC toggle. It disappeared somehow. Also find a good location for it.</del>
- <del>Heavy heavy refactoring of the JS, CSS, and PHP. It's extremely hack in a lot of locations. I've been cleaning it up from bottom up as I go, but there's a lot of code that was hacked for the sake of getting stuff done. I will consider this page done when I've refactored the code well enough to migrate it to the add character page.</del>

**Comment by bheiskell** [comment]
All currently available data is now in place on the page in a programmatically accessible format. Age and faction data is being placed in its proper place. The mvc side is mostly clean code now. The Javascript is about 50% refactored.

There's also a few bugs with the selectmenu I need to work on. Specifically, the menu not moving with the rest of the static elements when age is blurred. I may either trigger a window resize event; though that's rather hack.

**Comment by bheiskell** [comment]
Marked off several of the tasks listed above. The primary tasks that remain are writing functions to populate the race / location menus and creating a widget for profession data.
- IE doesn't render alpha correctly for stars. Turn alpha off on stars and find a better solution.
- There's a bug with the selectmenu that results in the dropdown not moving when an object further up the page changes height. I think I can fix this by moving the selectmenu list containers to after the selectmenu button and changing the positioning to be relative. This would require a decent amount of hacking around and might seriously break the layout. I need to brainstorm a work around for this.

**Comment by Treijim** [comment]
The stars are a graphical issue. Let the designer worry about that, unless it needs to be resolved quickly for some reason.

**Comment by bheiskell** [comment]
Just making a note so I don't forget. : )

**Comment by bheiskell** [comment]
Hacked together a prototype of the profession submenu. As soon as the profession menu is in place, I'm going to close this issue and open sub-issues on all remaining problems.

**Comment by bheiskell** [comment]
This task is essentially finished. Will close once I open sub-tasks for the remaining issues.

**Comment by Treijim** [comment]
I can't select a profession. If I move the cursor off a profession category, the options vanish. 

I also cannot select a faction rank, whereas I was able to at one point.

**Comment by bheiskell** [comment]
Opened subtasks for remaining issues. Closing this issue.
