### ISSUE TITLE
Location should have a widget

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#28]
Selecting a location should be fancy. Give it some sort of javascript widget.

**Comment by bheiskell** [comment]
Selecting

We could use a tree structure with + and - symbols to open and close locations, but the ipod style drill down seems most appropriate for selecting locations.

http://www.filamentgroup.com/lab/jquery_ipod_style_and_flyout_menus/
The breadcrumb example from above is really nice. I like how it gives you a history of what you've already selected. The disadvantage is it's a drop down. I really feel this should just take up a block of space like the next example. This also looks hard to extend.

http://www.barandis.com/dev/jquery/ddmenu/examples.html
Example II in the following toolkit gives the block style, but doesn't have bread crumbs. It's also really ugly, but I think styling could improve that.

Displaying

Both toolkits still lack a map option, but I'd have to extend any selecting option to get that functionality. I feel like for the top level areas simple images highlighting the region could work. Sub-regions could be done with more images. The issue becomes the cities/wilderness. I could do point locations for those or nothing at all. Need PM to weigh in on that.

http://www.tanabi.com/projects/imagemap
This toolkit is more for selecting than drawing.

http://plugins.jquery.com/project/maphilight
This looks similar to what we want. I don't know how he created the regions though. It looks like the same data that an image map uses though. There will also be conditions in which there wont be a region to highlight, e.g. wilderness. I think I can use this as an example of how to accomplish what we want.

**Comment by bheiskell** [comment]
Spoke with the PM a while ago. We agreed on a three tier drill down with an accompanying grouping that will contain the location information and a map.

The map will respond to the three different tiers in different ways. If nothing is selected the map is displayed in full. On hover or selection of the first area, the map will zoom and pan to the area. On hover on selection on the second area there is no map response (borders would be too much of a pain). On hover or selection of the third area a point will be displayed on the map.

Representing this data is painful to say the least. However it can be done. I believe the easiest way to do this is to have a point data and a percent width and height. 

For tier one, the point data will correspond to the top left point on the map and the percent width and height will be offsets describing the size of that location. Obviously I'm going to need an admin tool for drawing this rectangle. I really don't want to write this one, hahaha. For tier three there will only be point data.

For the sake of normalization, I'm going to break these two out into different tables. When the location data is pulled, if a location has entries it will be included as part of the meta data. If the metadata is set, then a location's map will pan and pin as expected.

**Comment by bheiskell** [comment]
This is still open because the widget is broken and parent regions don't propagate to children yet.

**Comment by Treijim** [comment]
Is this why the map isn't behaving properly? 

If I go to create a new story, the map is displayed off to the right at first. Selecting any country or province has the map display wrong areas. Also, I thought there were descriptions/icons at some point. Where did they go?

**Comment by bheiskell** [comment]
It only works in Chrome currently.

The top areas don't have descriptions. Child areas do have descriptions though.

**Comment by bheiskell** [comment]
The LocationInfo API doesn&#39;t make it clear that the width is for the image. I should fix that the next time I&#39;m tweaking that code. Set the width of the image to a third of the parent container&#39;s width to make the image fit. Tested it in all three browsers. Noticed a bit of lag on IE so I tweaked the jQuery animation interval.

Closed by 81b77c047abfba5a23ee0c0697f05fb87a3e1290
