### ISSUE TITLE
Entry Types

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#32]
- Narration: No avatars; fixed formatting (italics, different coloured font)
- Standard: Display character avatars, standard formatting
- Dialogue: No avatars 
- Combat: No avatars; OOC battle information
- Location Changes: Not normally accessible

**Comment by Treijim** [comment]
As a side issue, are we planning to display NPC avatars? Since there's currently no limit to NPCs, it's possible to have 15 in a story, following your character and all acting within one post. Perhaps just the NPC name is listed whenever they are mentioned?

**Comment by bheiskell** [comment]
I could actually do something where if there is going to be more than one character avatar, it shrinks them to half size.
