### ISSUE TITLE
Map residency to some sort of minimap

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#37]
When selecting or displaying a residency, it would be nice to have a corresponding map highlighting the selected region. 

Personally, I think it's too much to do selection from this map. At least for now.

**Comment by bheiskell** [comment]
PM: "Residency (country and/or province) is selected first, ideally from a minimap,"

**Comment by Treijim** [comment]
Would this be the same map used to set the location of threads? I think a map with all countries and provinces/regions marked would be sufficient and I can make it quite easily since my current version is vectorised. Currently, the forums have countries and only provinces in terms of North Nidonn. Since then, Riiga has become more defined.

**Comment by bheiskell** [comment]
I was actually thinking about that. In this case I think it might be better if it isn't the same map. Highlighting the full region, I think, would reduce mistakes about where a user places their character.

Do you mean just have a big map with all the locations on it?

**Comment by Treijim** [comment]
Residency is only country, right? Thread location is currently set in provinces within countries. So you're right, perhaps two maps are needed; one with countries and another with provinces and perhaps cities. How does that sound?

**Comment by bheiskell** [comment]
Sounds great to me. I'll stick with that then.

**Comment by bheiskell** [comment]
I think I'm going to try to leverage the locations widget to perform this task. That means I need to code it in such a way that it can be reused. I think I'll build a specific location map widget that all it does is pan around the map and drop dots on it based on data given to it.

**Comment by bheiskell** [comment]
Josh, should the residency be loaded in the view character page? Meaning should it have a map panned to the right area?

**Comment by Treijim** [comment]
Yeah, I think it should.

**Comment by bheiskell** [comment]
Although it's not being used everywhere yet, I have the helper created. Resolving.
