### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#39]
PM: "Currency is dependent on location of character (clicking Currency anywhere will bring the user to a conversion page)"

**Comment by bheiskell** [comment]
Oh dear god. Hahaha.

**Comment by Treijim** [comment]
I'm starting to think currency/wallet can be avoided altogether. Looking for your thoughts on this, so we can discuss its practicality and actual relevant uses.

**Comment by bheiskell** [comment]
I'm actually ok with keeping this feature. Currency conversion is plausible, but I'd advise against it. It's an annoying issue in general. 

There really aren't any possible uses for it though, because you sort of make up their inventory in the description process. Did you have any ideas?

**Comment by Treijim** [comment]
Yeah, it's gimmicky in retrospect. Avoid it/move it/remove it, whatever is easiest, entirely for now.
