### ISSUE TITLE
Research and attempt to leverage admin routing

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#44]
There's too many admin functions now. They need to have clear separation if possible. Assuming it doesn't require complex ACLs, admin routing would be our preferred route.

**Comment by Treijim** [comment]
What's an admin function and what are they?

**Comment by bheiskell** [comment]
Location_tags. Only you can create them. This was a more note to self. : )

**Comment by bheiskell** [comment]
Admin routing now in place for all admin specific duties.
