### ISSUE TITLE
Character Drafts and Limits

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#46]
I'm not sure if it's already listed, but an author can only have as many characters as they do rank stars. That means, initially, you can only create one character. When you reach rank two, you can have two, and so on. 

Similarly, is it reasonable to allow people to create draft characters and submit them as drafts to be worked on/submitted at a later point, or when they are actually able to submit them? If they click Create a Character and they are at their character limit, there should be a message on the character creation page telling them that they must save this character as a draft until they have enough rank to submit it for acception. Maybe other authors can comment on character drafts too?

**Comment by bheiskell** [comment]
I really need to separate the character and character draft sections. I haven't exactly come up with a clean way to do that yet.

**Comment by bheiskell** [comment]
I'm ditching the draft idea atm. The pending character stuff is completed. I suspect there are little issues, but I'll open new bugs as I find them.
