### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#47]
Upon receiving a promotion, the following should be displayed:
- Characters that can gain a level (show old level)
- Characters that can gain a faction rank
- All locations now available for new characters (indexed by level required)

**Comment by Treijim** [comment]
All minus the third one. There is really no reason to change the residence of a character via their profile, as it doesn't really affect anything.

**Comment by bheiskell** [comment]
I thought the purpose was to show them new places they could create characters.

**Comment by Treijim** [comment]
It doesn't affect anything, so it isn't needed. Giving a character a new residency/hometown (which doesn't make sense anyway) doesn't actually change anything.
