### ISSUE TITLE
Descriptions are needed for Factions and Races

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#48]

**Comment by bheiskell** [comment]
PM: Can you get this info ready and I'll update the web ui for you?

**Comment by Treijim** [comment]
Yeah. I'll write it all up soon.

**Comment by Treijim** [comment]
Done factions. Working on races.

**Comment by bheiskell** [comment]
Reminder that this issue is still on your plate. :-)

**Comment by Treijim** [comment]
I believe you have the information now. :)

**Comment by bheiskell** [comment]
Correct.
