### ISSUE TITLE
Ordering of Items in Character Wizard

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#51]
Human needs to be above Ildemin.

Locations should be as they are on the Locations list (level 1s only, the rest are fine because they're essentially listed in order of their required rank). 

The rest is fine.

**Comment by bheiskell** [comment]
Fixed data issue with Sirin and Trueblood being in both areas of Huiron. Fixed an ordering issue with the data being pulled down for the character's page. Closed by 61002ee00bb482f83ca5717fe109a1b38e7642f1
