### ISSUE TITLE
Allow users to select a faction rank

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#55]
Enable users to select a faction rank after selecting a faction.

Currently, this isn't possible because the faction rank is not being stored. It was being calculated based on the user rank and age of the character.

Just to check, do we want to support a character having multiple factions? That influences design decisions moving forward.

**Comment by Treijim** [comment]
How about they are able to have one secret and one normal faction at the maximum? This is ideal and realistic, but not absolutely necessary. If it's easy enough to implement, I'll leave it up to you and I'll just add the details myself for you.

**Comment by bheiskell** [comment]
I dislike that idea; I'd prefer either support one or many. Half way will likely lead to a change in the future requiring more of one or the other and numerous hacks to support it.

**Comment by Treijim** [comment]
We'll do support for one, then. Hidden factions are added per character, remember.

**Comment by bheiskell** [comment]
Just to be sure, supporting one would result in a hidden faction offer overwriting their initial faction selection.

**Comment by Treijim** [comment]
Yep. But the idea is that they can go back and select their old faction and rank later if they choose to, right? 

Just thought of character edit permissions. Example, a user cannot edit a character once it's been accepted; the admin has to do it on request, or the user submits a request form, to prevent them from changing their character's aspects nonsensically. Do I need to create a new issue for this?

**Comment by bheiskell** [comment]
Yes, and they'll still be allowed to select the hidden faction for that character, should they choose to rejoin it.

Regarding permissions, see issue #3.

**Comment by bheiskell** [comment]
This issue has been resolved closing in favor of #50.
