### ISSUE TITLE
Star ranking should be displayed when displaying an author's name

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#6]
I'd like to replicate the existing forum's approach. When displaying an author's name in a story or on their profile, it should display their rank as well.

**Comment by bheiskell** [comment]
I need PM / designer to weigh in on this. Where / how should this be displayed. Take a look at the current view story and let me know where (if at all) you'd like ranking stars to be displayed.

Currently, 7 stars is 16 \* 7 px wide which exceeds the user avatar width of 100px (this means it looks bad).

**Comment by bheiskell** [comment]
PM, need feedback on this one.

**Comment by bheiskell** [comment]
Just making a note, perhaps doing a star icon with a number in it instead of the number of stars would look better. Not certain. Still need PM's feedback on this.

**Comment by Treijim** [comment]
Use smaller stars? 14 pixels wide if my maths is good.

**Comment by bheiskell** [comment]
Resized the display stars to only take up 14 pxs. The selection stars for the character wizard is still 16x16. Closed by e809b3dc15abe577e2799a2c3e68ed259db5f8ba
