### ISSUE TITLE
Stories and NPCs

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#63]
Could we have two primary differences:

The first is that NPCs must be "associated" or connected to one or more PC profiles. On labelling a character as an NPC, the author can select from the list of their PCs which character(s) are associated with the NPC. 

The second is that when labelling which characters a post involves, you cannot select NPCs. They may only involve PCs. I'm not sure how well this second one will work, but I'm open to discussion.

**Comment by bheiskell** [comment]
I'd like them to be able to tag NPCs in case that NPC is talking. Why would you want otherwise?

**Comment by Treijim** [comment]
The second idea is based on the assumption that you can't post a post without tagging any characters; it's to prevent an author from creating a thread where there are no PCs. It defeats the purpose of the NPC if they can be used like a PC.

**Comment by bheiskell** [comment]
How about instead, I make it so you can't post unless you have one character in the story that's not an NPC. Then when you add characters it will prompt you for if you want to bring the character's NPC into the story.

**Comment by bheiskell** [comment]
I say this because I can imagine posts that don't actually involve the user's character, so I don't want to make tagging a user a requirement.

**Comment by Treijim** [comment]
You mean, when you select related characters in each post, you must select at least one NPC? What do you mean by "when you add characters"? Do you mean when you select them from the related characters list? I'm not sure what you're referring to.

**Comment by Treijim** [comment]
Let's go with your idea. You can't post unless you have at least one character in the story that's not an NPC.

**Comment by bheiskell** [comment]
Noting, to complete this task:
- A user must join a story and have one character in it to post
- A user may only add NPCs once a PC has been added to the story
- Ideally, when adding a PC, there will be a prompt suggesting the addition of related NPCs

**Comment by bheiskell** [comment]
Closing in favor of #66
