### ISSUE TITLE
NPCs

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#66]
- NPCs shouldn't count against the player when determining if they can create a new character.
- Add another column called parent_character_id that only applies to NPCs
- Display a list of NPCs on the view character page
- Display NPCs by their parent character on the view character page. [1]
- When adding a PC to a story, the user is then prompted to add NPCs

[1] Probably the best way to do this is add a class to that TR that indents the character name / avatar.

**Comment by Treijim** [comment]
As a suggestion, when one views a member profile, they see a list of that member's characters. Beneath each character, in new rows with inset names, are related NPCs. 

Example:

Evan
         Esmond
         Steele
Cole
         Gideon

... Or something like that. This is a lower priority addition, if we're going to add it.

**Comment by bheiskell** [comment]
Concept of promotion out of NPC state and the concept of changing NPC ownership to another character.
