### ISSUE TITLE
Calculate author's rank

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#7]
Need a central location for calculating an author's rank.

**Comment by bheiskell** [comment]
PM: "Ranks based on how many posts one has made (Foreigner, 20 Commoner, 50 Citizen, 100 Soldier, 225 Guard, 400 Knight, 600 Commander)"

**Comment by bheiskell** [comment]
There needs to an offset / import feature to enable past users to keep their star rating.

PM: "A rank offset, or superficial post offset, applyable by admins eg: +40 or -12"

**Comment by Treijim** [comment]
Don't forget to make somebody with 0 posts an "Observer" so it's easier to see who is active on the forum and who is just watching.

**Comment by bheiskell** [comment]
Noted. Thanks!

**Comment by bheiskell** [comment]
Ranking based on # of posts is in place. Offset not in place yet. Also need to check if the user is an admin to default them to rank seven.

**Comment by bheiskell** [comment]
Offset in place. Admin defaulted to seven. There's no place on the web interface to set this offset. Will open a new issue when that's needed.
