### ISSUE TITLE
Graphics needed before release

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#71]
PM, I don't have the copyright to use the images I am currently using as filler. We still need:
- 100x100 default user png
- 75x75 default character png
- 16x16 favicon

I could put something together, but I suspect you or your brother would do a better job.

**Comment by Treijim** [comment]
http://treijim.penscribbles.com/Images/favicon.ico

http://treijim.penscribbles.com/Images/defaultuser.png

http://treijim.penscribbles.com/Images/defaultchar.png

**Comment by bheiskell** [comment]
Not to be picky but can the user/character avatars actually look like people, kind of like it is now? I don't want to encourage people to just put arbitrary icons up for their characters. We want it to either be the default, like most of the characters will be since we imported them, or a drawing of the character. Right?

**Comment by Treijim** [comment]
I was going to do people, but I'd have to pick a gender unless I basically cloned the current avatar, which is barely worth me doing it. If we really wanted to encourage people to put drawings in their avatars (I assume you don't want copyrighted material on the site, and many of our members cannot "draw") we may as well put "insert avatar here" or "insert character here" for the avatars.

**Comment by bheiskell** [comment]
I hate to say it, but that actually tends to be more legally ok. I wont get a take down request for an avatar. Using someone else's default icons I might though.

**Comment by bheiskell** [comment]
Installed the favicon and defaultuser.png. I'd still like to see a profile like icon for the character. Maybe even for the user too, but that's a design decision. 0.2

**Comment by bheiskell** [comment]
Closing in favor of #121
