### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#78]
I believe only a minority of our users use the YY-MM-DD format. I use the DD-MM-YY format, so an option to change it would be very handy and far less confusing.

Are you planning on implementing timestamps? I forget.

**Comment by bheiskell** [comment]
I agree. I'll flip them around.

There are timestamps on everything. It's just a matter of displaying them where appropriate.

**Comment by bheiskell** [comment]
Closed by 4412a328b195dd292776d7681bafb5d0779b8475
