### ISSUE TITLE
Chat Box

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#8]
Need a cbox equivalent for the forums.

In initial versions, just embedding a cbox might work, but we could make this significantly more powerful. By tying usernames to chatbox comments, we could offer the ability to include links to the user's characters or stories just by clicking a few buttons.

Use case:
Author goes to make a comment. Types, "Hey guys, check out my new character ". Then the author could select insert > character > selects character name. The final text would be, "Hey guys, check out my new character character_id:12". This prefix could then be translated to a hyper-link.

Final version would require RSS.

**Comment by Treijim** [comment]
I would like to be able to use this chat box to make stickied announcements, too. This would be very handy for me.

**Comment by bheiskell** [comment]
Will move this to beta once it's embedded in the default layout.

**Comment by bheiskell** [comment]
Indicate the user should log in to comment.

**Comment by bheiskell** [comment]
Initial features have been completed. Advanced features will be moved to 1.0.

**Comment by bheiskell** [comment]
Added a chat box to the footer. Closed in 0f81c5397a52893bb8ac8f0d7ae62aa38db30dd3 & 92d2763a75d976de3d8df79ac498cbe61e8a4e07
