### ISSUE TITLE
Question: Ignore invite only and NPC associations for 0.1?

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#80]
Can I ignore invite only and NPC for 0.1 and push that feature to 0.2?

That will reduce the work required for release significantly. I figure those features will not be in immediate demand, but I may be mistaken.

**Comment by Treijim** [comment]
Sure. Postpone it. 

Just to clarify: once NPC association is implemented, everyone would have to edit their characters again, right?

**Comment by bheiskell** [comment]
Only if they have NPC's, which to my knowledge is a new feature to non admin users.

**Comment by bheiskell** [comment]
Closing. Reopen if you have questions or want to make further clarifications.
