### ISSUE TITLE
Allow selecting a faction rank

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#82]
Backend wise this is just another column. I'm not sure how to accomplish it from a UI perspective.

**Comment by Treijim** [comment]
Can't you just make it so the user can click on the rank on the table which appears to the right?

**Comment by bheiskell** [comment]
It would be cumbersome from a UI perspective. The drop down is hover and moving right to select a option would result in a lot of mistakes. I think the simplest thing is to just have another drop down below it. That will take time to code in more enforcement of the rules, but I can do it.

**Comment by bheiskell** [comment]
Implemented the javascript rules for the subrace and faction ranks fields.

The final JavaScript became a little bit hack as there were a few features that needed to be hammered into place. A refactor at this point would not be cost beneficial. Will revisit if/when new functionality is required.

Closed by f3f78c5a24f15d68b9dec790e17f64e8db5106b1
Closed by f3f78c5a24f15d68b9dec790e17f64e8db5106b1
