### ISSUE TITLE
Question: Programmatic restriction of double posts

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#85]
Should we programmatically restrict users from posting two entries in a row?

**Comment by Treijim** [comment]
Yes. There's no reason to do this since people can edit previous posts.

**Comment by bheiskell** [comment]
Good. I have a fix ready to commit for this.

**Comment by bheiskell** [comment]
Disable double posting. Closed by f4c06ce11011631a75ebefbcebf286b0cc210d06
