### ISSUE TITLE
Rotate turns after each post

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#86]
Allow the user to select the next user to post. Default this field to the next in the list.

**Comment by Treijim** [comment]
This is a good idea but it's a low priority.

**Comment by bheiskell** [comment]
It's almost the same amount of work to allow the user to select a turn.

**Comment by bheiskell** [comment]
Fixed a few slugging issues; there are still more.

Implemented a rudimentary turn cycling, that needs work. I hate the way this is being done; I need to plan this out more. Also, I need to send out messages to members of the story when an entry is posted.

Implemented some basic controls to limit a user from adding a character to multiple stories. The backend code is a bit gross, but it works.

Also removed two unused actions (whoops).

Closed by e918dad6551ee72f345522053f347fe29e6b3b89
Closed by e918dad6551ee72f345522053f347fe29e6b3b89
Closed by e918dad6551ee72f345522053f347fe29e6b3b89
