### ISSUE TITLE
After critical steps like registration or character creation, redirect to pages with helpful info.

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#87]
I have the base text written up for these tasks. Registration, character creation, character acceptance, and story creation all warrant some explanation, I think.

**Comment by Treijim** [comment]
Definitely a requirement. Am I able to edit those pages whenever I please? That would be an ideal setup.

**Comment by bheiskell** [comment]
Ideal, but painful. I'd like to create a wiki section for you, but that will come later.

**Comment by Treijim** [comment]
Sounds good. Set it aside for later.

**Comment by bheiskell** [comment]
Added message notifications in a few areas. Added a few redirect to new static content pages. These could use a bit of work, but the base idea is there. The post registration page is now instructions on what to do next. More help information needs to be scattered throughout; see issue #65

Closed by c6d02531d2b15aeabac55114f300f0ed17edf6ea
Closed by c6d02531d2b15aeabac55114f300f0ed17edf6ea
Closed by c6d02531d2b15aeabac55114f300f0ed17edf6ea
