### ISSUE TITLE
List only characters available when joining

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#88]
Also, provide an explanation when no characters are available. Perhaps even identify which story the character is in and provide a link to remove that character.

**Comment by Treijim** [comment]
The title is a good idea. The rest is also good, but of lower priority.

**Comment by bheiskell** [comment]
Fixed a few slugging issues; there are still more.

Implemented a rudimentary turn cycling, that needs work. I hate the way this is being done; I need to plan this out more. Also, I need to send out messages to members of the story when an entry is posted.

Implemented some basic controls to limit a user from adding a character to multiple stories. The backend code is a bit gross, but it works.

Also removed two unused actions (whoops).

Closed by e918dad6551ee72f345522053f347fe29e6b3b89
Closed by e918dad6551ee72f345522053f347fe29e6b3b89
Closed by e918dad6551ee72f345522053f347fe29e6b3b89
