### ISSUE TITLE
Question: Story comments

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#90]
Are story comments needed or is the chat box sufficient? How would you like that to work?

**Comment by Treijim** [comment]
Story comments are needed, especially in my case; running a dozen different plots is tough on the brain. 

I think several options are needed. A public box for any forum members for OOC comments is quite useful. A private box only readable by members of that thread would also be useful, but that one is not so necessary. What would be most useful to me is a more private box for notes for myself. 

All of these can either be global per thread or attached to posts. Perhaps the boxes can be beneath the main text box when you post a new entry. If they're going to be attached to posts, perhaps a way to easily find them would be good, but that part is probably a feature for later. Finding my private notes on post 116 of Gondarash probably won't be easy if I forget which post it's on.

**Comment by bheiskell** [comment]
Yeah I think comments on posts is probably overkill. There is an outstanding request for [This is an OOC comment note] that would be hidden and made visible at the bottom of an entry.

I think a public thread chat should suffice. I can't imagine a reason why that chat would be private. That way even non-authors can comment.

What you want is a private notes option. That's not impossible. If you want that, make a new issue explaining how you want it to work. I'll tag it for the 1.0 release.

**Comment by Treijim** [comment]
What's the difference between comments on posts and OOC comments, both of which you mentioned in your first paragraph? People currently use OOC comments in their threads, but it's just plain text inside the post. 

Chats could be private so that potential spoilers don't become public and ruin the story for readers.

**Comment by bheiskell** [comment]
OOC is as it is now. Comments on a particular post is where anyone can do it. I think that would be hard to do, because it would be awkward to pull down that data.

How about particular chat posts can be private. They'll show up in a different color and there will be a little check box for private when commenting.
