### ISSUE TITLE
Bug: Page not loading

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#99]
I was editing Esmond: http://riiga.net/characters/edit/77 and I forgot to set a subrace. It told me I needed to select a subrace, so I did so, and clicking Submit made the page go blank. The URL was the same. Going back a few steps and doing it over again fixed it. 

You may or may not want to look into that.

**Comment by bheiskell** [comment]
I can't replicate. When you say blank, you mean it didn't load anything?

**Comment by Treijim** [comment]
Well the URL did not change at all, so technically, it wasn't attempting to reload anything. It just blanked out the entire page. I'll try and help you replicate the issue soon.

**Comment by bheiskell** [comment]
Leaving open. Expire the issue if no further action has occurred in 3 months.

**Comment by bheiskell** [comment]
Mega hack to deal with the same option showing up in two optgroups. Considering both cakephp and jquery don&#39;t know how to deal with disabled options, I&#39;m thinking this might be undefined behavior. Either way, I should come back and refactor this code to not be divided into two optgroups, or have the relationship between the factions and races be unique in this select drop down. PM let me know if you still have issues. Closed by 057d424503d0e5a1b77f6cb0ee6dbc90833bbdae Closed by 057d424503d0e5a1b77f6cb0ee6dbc90833bbdae
